# Generated by Django 6.0 on 2026-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_table_occupied_remove_table_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tables',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
