# Generated by Django 6.0 on 2025-12-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='key',
            new_name='val',
        ),
    ]
