# Generated by Django 6.0 on 2026-05-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_restaurant_seats_remove_restaurant_tables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='password',
        ),
    ]
