# Generated by Django 6.0 on 2025-12-28 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_key_table_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='table',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='accounts.table'),
            preserve_default=False,
        ),
    ]
