# Generated by Django 6.0 on 2026-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_globaluser_options_alter_globaluser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaluser',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
