# Generated by Django 6.0 on 2026-05-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_globaluser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaluser',
            name='username',
        ),
    ]
