# Generated by Django 6.0 on 2026-05-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_globaluser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globaluser',
            old_name='name',
            new_name='username',
        ),
    ]
