# Generated by Django 6.0 on 2026-05-15 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_name_globaluser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='pin',
            new_name='pincode',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gstId',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=dict)),
                ('seats', models.JSONField(default=list)),
                ('bill', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='accounts.restaurant')),
            ],
        ),
    ]
