# Generated by Django 6.0 on 2026-05-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='accounts.restaurant'),
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='accounts.restaurant'),
        ),
    ]
