# Generated by Django 6.0 on 2026-05-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_menu_restaurant_alter_table_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
