# Generated by Django 6.0 on 2026-05-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_orders_items_alter_restaurant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
