# Generated by Django 6.0 on 2026-05-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seat_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='seats',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
