# Generated by Django 6.0 on 2026-05-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_reviews_order_alter_orders_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.orders'),
        ),
    ]
