# Generated by Django 6.0 on 2026-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_reviews_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='base_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
