# Generated by Django 6.0 on 2026-05-27 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_menu_base_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='arrival',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
