# Generated by Django 6.0 on 2026-05-31 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_orders_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arrival',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
